### ISSUE TITLE
Model nowhere to be found.

### ISSUE THREAD

**Issue by bobvdvalk** [DataDo/slim#2]
Hi,

I've made a model:

```
class TicketModel
{
    private $id;
    public $title;
    public $description;
    public $file;
    public $status;
    public $urgency;
    public $datetime;
    private $client_id;
}
```

And I have added slim to my index file.

```
$repo = new Repository(TicketModel::class, $pdo, 'id');
$app = \DataDo\Slim::create($repo);


$app->run();
```

But when I do a web request to 

> http://domain.com/TicketModel/
> or
> 
> http://domain.com/TicketModel/1

I still get the 404 page.
Am I doing something wrong or is it a error?

Thanks

**Comment by bobvdvalk** [comment]
repo: https://github.com/bobvdvalk/scaling-happiness

**Comment by ChappIO** [comment]
The url you should visit is http://domain.com/TicketModels/1

Note the s

**Comment by bobvdvalk** [comment]
Thanks for your help!
